/*
   Implementing a c program called as generate.c
  It generates pseudorandom numbers in [0,MAX] one per line.
  where n is number of pseudorandom numbers to print
  and s is an optional seed
 */
 
#define _XOPEN_SOURCE

#include <cs50.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// upper limit on range of integers that can be generated
#define LIMIT 65536

int main(int argc, string argv[])
{
    //Checking if the number of arguments are neither of 2 or 3 and accordingly printing something
    if (argc != 2 && argc != 3)
    {
        printf("Usage: ./generate n [s]\n");
        return 1;
    }

    // If number of arguments are 2 or 3 then converting second argument into a integer and storing its int value in n
    int n = atoi(argv[1]);

    /*
   # If number of arguments are 3,
    then passing long int conversion of third argument,
    received by main in srand48 function...
   # If number of arguments are 2,
   then passing time function,,
   with null argument as argument in srand48 function
    */
    
    if (argc == 3)
    {
        srand48((long) atoi(argv[2]));
    }
    else
    {
        srand48((long) time(NULL));
    }

    // Printing all the random numbers generated by drand48 function
    for (int i = 0; i < n; i++)
    {
        printf("%i\n", (int) (drand48() * LIMIT));
    }

    // Success
    return 0;
}
